### PR TITLE
Switch build to rspack and add react-fast-refresh

### PR DESCRIPTION
**Pull request by chrisirhc**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

[Rspack](https://rspack.dev/) is rust-based web bundler that's intended to be a drop-in replacement for webpack that's fast.
The addition of [react-fast-refresh](https://rspack.dev/guide/tech/react#fast-refresh) now allows refreshes of React components in-place while the application is loaded without refreshing the page/window.

What I've tested so far manually:
- [x] `npm run start:dev`
- [x] `npm run dist:mac`

TODOs:
- [ ] Clean up commits
- [x] Remove unrelated gist commits
- [x] Add video demo of react-fast-refresh
- [ ]  Validate all rspack package.json scripts are working

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [ ] 🔁 CI

### Mobile & Desktop Screenshots/Recordings
https://github.com/user-attachments/assets/6cd24be9-2f8a-4f7d-9955-5fd43848354e

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by chrisirhc** [comment]
Not sure what happened to #1039 , the github actions bot limited it to my interactions after I accidentally clicked Close. I can't do anything with that PR. If anyone can close it for me that'd be great.

**Comment by chrisirhc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chrisirhc** [comment]
recheck

**Comment by ra3orblade** [comment]
Hello, thanks for the PR, I've checked the branch but `npm run start:dev` does not work through rspack, it is used for development purposes. And need to check the CI pipeline as well.

**Comment by chrisirhc** [comment]
> Hello, thanks for the PR, I've checked the branch but `npm run start:dev` does not work through rspack, it is used for development purposes. And need to check the CI pipeline as well.

Could you please share the error you're seeing?
I'm using that command to check and it works for me.

**Comment by chrisirhc** [comment]
Took a first pass at cleaning up the PR so it's ready for a first review and comment.

**Comment by ra3orblade** [comment]
> > Hello, thanks for the PR, I've checked the branch but `npm run start:dev` does not work through rspack, it is used for development purposes. And need to check the CI pipeline as well.
> 
> Could you please share the error you're seeing? I'm using that command to check and it works for me.

it works, but it works through webpack

**Comment by chrisirhc** [comment]
> It works, but it works through webpack, maybe I didnt get something. I'll check again. Could you please rename webpack in all commands so it would be clear it's not webpack anymore?

webpack-dev-server@5 is in use by rspack/server as per [the documentation here](https://rspack.dev/guide/features/dev-server#:~:text=webpack%2Ddev%2Dserver%405%20is%20used%20in%20%40rspack/dev%2Dserver).

I'm not sure if that's what you meant. I can rename the remaining occurrences of webpack.

**Comment by ra3orblade** [comment]
> > It works, but it works through webpack, maybe I didnt get something. I'll check again. Could you please rename webpack in all commands so it would be clear it's not webpack anymore?
> 
> webpack-dev-server@5 is in use by rspack/server as per [the documentation here](https://rspack.dev/guide/features/dev-server#:~:text=webpack%2Ddev%2Dserver%405%20is%20used%20in%20%40rspack/dev%2Dserver). Is that what you meant?
> 
> I can rename the remaining occurrences of webpack which are in 3 package.json scripts. It's used in the name of the script.

I see, yes rename scripts pls.

**Comment by ra3orblade** [comment]
@chrisirhc merged, thanks! The code reload now works **really fast**.

**Comment by fuksman** [comment]
@any contributor @chrisirhc tooling

**Pull request merged**
