### PR TITLE
Fixing kanban overflow

### PR DESCRIPTION
**Pull request by Lite5h4dow**
### Description
This PR adds a scrollbar to the kanban board, and lets the height of the rendered area take precidence. this might want to be made optional by moving the options into a class. 

### What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents
[Community Post](https://community.anytype.io/t/fixing-kanban-overflow/11007)

### Mobile & Desktop Screenshots/Recordings
image

image

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help (not sure if you have UI Tests)

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by ra3orblade** [comment]
This kind of CSS formatting is not accepted.

**Comment by Lite5h4dow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Lite5h4dow** [comment]
> This kind of CSS formatting is not accepted.

might i ask why? its easier to read.

**Comment by Lite5h4dow** [comment]
ill fix it regardless, just curious

**Comment by ra3orblade** [comment]
it's not easier to read.

**Comment by ra3orblade** [comment]
Check out your changes, like how do I suppose to make a review with this formatting changes without actual understanding what your fix is? https://github.com/anyproto/anytype-ts/pull/286/files

Any code formatting changes won't be accepted.

**Comment by fuksman** [comment]
@Lite5h4dow, please also review the authorship of the commits. It appears that one commit was made by an author who doesn't have a GitHub account. A GitHub account is required to sign the CLA, so please either [add an additional email address](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to your account or remove the commit from the unrecognized author. Thank you!

**Comment by Lite5h4dow** [comment]
Im going to close this PR, and rebase this branch to another to fix commit issues with unknown account.

**Pull request closed without merging**
