### PR TITLE
Add missing files to gitignore

### PR DESCRIPTION
**Pull request by developomp**

### CODE REVIEW

**Comment by ra3orblade** [comment]
Looks good, I think you can add `*.yml`, `*-unpacked` as there are no files with that names.

**Comment by developomp** [comment]
Done :+1:
Did the same things for `*.yaml` and `*-arm64` too.

**Comment by ra3orblade** [comment]
> Done 👍 Did the same things for `*.yaml` and `*-arm64` too.

Thanks, I will merge it when I will have permission to merge public PRs

**Comment by fuksman** [comment]
recheck

**Comment by developomp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ra3orblade — APPROVED** [review]

**Pull request merged**
