### PR TITLE
Tidy up dist/lib gitignore

### PR DESCRIPTION
**Pull request by developomp**
- cleaner gitignore structure
- prvent files from showing up on git status after running `update.sh`

### CODE REVIEW

**Comment by ra3orblade** [comment]
This is incorrect, directory structure should stay intact, your PR removes lib entirely.

**Comment by developomp** [comment]
I think it's pretty safe to delete them. They get repopulated after running the `update.sh` script anyway. I don't see the point in keeping them.

**Comment by ra3orblade** [comment]
They are now used in localisation update mechanism.

**Comment by developomp** [comment]
My main concern is that every time someone runs `update.sh` or `npm run start:dev`, it makes `git status` messy.

**Comment by ra3orblade** [comment]
> My main concern is that every time someone runs `update.sh` or `npm run start:dev`, it makes `git status` messy.

could you show example?

**Comment by developomp** [comment]
image

**Comment by ra3orblade** [comment]
`https://github.com/anyproto/anytype-ts/commit/143e751ab07cbe98028a8e759620db1b445dddca` this fixes the above screen shot, but actually if you want to make command for updating without changing the update.sh is just `update.sh && git checkout . && git clean -df`

**Comment by developomp** [comment]
Verified that 143e751ab07cbe98028a8e759620db1b445dddca fixed the issue. Thanks!

**Pull request closed without merging**
