### PR TITLE
Feature/JS-4830: Inline latex

### PR DESCRIPTION
**Pull request by ra3orblade**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by PeterWang-dev** [comment]
Is there any progress on this pr? How long will it take about to merge into main? Thanks for your contributions.

**Comment by ogcatt** [comment]
bump

**Comment by kellertuer** [comment]
Any progress on this?
I miss this feature really really a lot (I work in mathematics).

**Comment by ra3orblade** [comment]
> Any progress on this? I miss this feature really really a lot (I work in mathematics).

No progress on this because it needs development on other platforms as well and this leads to complications.

**Comment by kellertuer** [comment]
That is sad to read, this is a main feature I miss to move to mainly using Anytype. Nearly all my notes include inline math.

**Comment by alvorithm** [comment]
Lack of math support is also a showstopper for my usecases, but I am grateful that @ra3orblade is giving us a clear signal that this won't happen soon.

**Comment by mathias-ewald** [comment]
Any updates?

**Comment by kellertuer** [comment]
If you read here
https://community.anytype.io/t/inline-latex-addition/2315/89
carefully, this feature is probably not coming anytime soon, it is somewhere between “no one needs this” and “yes, some might maybe need this, but it'c complicated so we do that maybe in some unforeseeable future time”.

**Comment by mathias-ewald** [comment]
So many places to find information 🫨

**Pull request merged**
