### PR TITLE
Modify markdown's format reg

### PR DESCRIPTION
**Pull request by LavaCxx**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description
The underscore parsing`_x_ or __x__` will only be enabled in the case of beginning or prefixing spaces.

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents
#530 

### Mobile & Desktop Screenshots/Recordings
gif

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by te-ce** [comment]
Oh yes please!

**Comment by ra3orblade** [comment]
Why does it work like this only for underscore?

**Comment by LavaCxx** [comment]
> Why does it work like this only for underscore? And it won't work when you have multiline text and you try to start from the beginning.
> 
> ```
> String 1
> _underline_ string 2
> ```

I checked other markdown editors and found that indeed only underscore applies this rule.
As for the second question, I tried it and the Markdown format was parsed normally.
ss

**Review by ra3orblade — APPROVED** [review]

**Comment by fuksman** [comment]
@any contributor @LavaCxx code

**Pull request merged**
