### PR TITLE
Extend Readme to copy anytypeHelper into dist

### PR DESCRIPTION
**Pull request by negue**
As mentioned in #94 and #92 this adds the information that the binary needs to be moved when running it locally.

### CODE REVIEW

**Comment by negue** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ra3orblade** [comment]
Add commands for all platforms pls

**Comment by negue** [comment]
Added a table overview of the commands and updated the gitignore because the `update.sh` also accepts `arm`/ `amd` without `64`

I would've added the commands to move them from the `anytype-heart` too, but I couldn't get the `make install-dev-js` command to work :/

**Review by ra3orblade — APPROVED** [review]

**Comment by ra3orblade** [comment]
> Added a table overview of the commands and updated the gitignore because the `update.sh` also accepts `arm`/ `amd` without `64`
> 
> I would've added the commands to move them from the `anytype-heart` too, but I couldn't get the `make install-dev-js` command to work :/

thanks, merged

**Pull request merged**
